export default defineAppConfig({
  boilerplateDocs: {
    site: {
      name: 'Nuxtbe',
      description: 'Beautifully designed Nuxt Content template built with shadcn-vue. Customizable. Compatible. Open Source.',
      ogImage: '/hero.png',
      ogImageComponent: 'ShadcnDocs',
    },
    theme: {
      customizable: true,
      color: 'zinc',
      radius: 0.5,
    },
    header: {
      title: 'Nuxtbe',
      showTitle: true,
      border: false,
      logo: {
        light: '/logo.svg',
        dark: '/logo.svg',
      },
      darkModeToggle: true,
      nav: [
        {
          title: 'Home',
          to: '/',
          target: '_self',
          showLinkIcon: false,
        }, {
          title: 'Docs',
          links: [{
            title: 'Getting Started',
            to: '/docs/getting-started',
            description: 'Start building your project with Nuxtbe',
          }, {
            title: 'Guide',
            to: '/docs/guide',
            description: 'Follow our guides to accelerate your development.',
            target: '_self',
          },
          {
            title: 'Components',
            to: '/docs/components',
            description: 'Here you can find all the components used in the boilerplate.',
            target: '_self',
          },
          {
            title: 'Examples',
            to: '/docs/examples',
            description: 'Just copy and paste the code to your project.',
            target: '_self',
          }],
        }, {
          title: 'Blog',
          to: '/blog',
          description: 'Read our latest blog posts.',
          target: '_self',
          showLinkIcon: false,
        }, {
          title: 'Changelog',
          to: '/changelog',
          description: 'Read our latest changelog.',
          target: '_self',
          showLinkIcon: false,
        }],
      links: [{
        icon: 'line-md:github-loop',
        to: 'https://github.com/Nuxtbe/nuxtbe',
        target: '_blank',
        tooltip: 'Check out our latest changes on GitHub repository',
      }],
    },
    aside: {
      useLevel: true,
      collapse: false,
    },
    main: {
      breadCrumb: true,
      showTitle: true,
      codeCopyToast: true,
      codeCopyToastText: 'Copied to clipboard!',
      fieldRequiredText: 'required',
      codeIcon: {
        'package.json': 'vscode-icons:file-type-node',
        'tsconfig.json': 'vscode-icons:file-type-tsconfig',
        '.npmrc': 'vscode-icons:file-type-npm',
        '.editorconfig': 'vscode-icons:file-type-editorconfig',
        '.eslintrc': 'vscode-icons:file-type-eslint',
        '.eslintrc.cjs': 'vscode-icons:file-type-eslint',
        '.eslintignore': 'vscode-icons:file-type-eslint',
        'eslint.config.js': 'vscode-icons:file-type-eslint',
        'eslint.config.mjs': 'vscode-icons:file-type-eslint',
        'eslint.config.cjs': 'vscode-icons:file-type-eslint',
        '.gitignore': 'vscode-icons:file-type-git',
        'yarn.lock': 'vscode-icons:file-type-yarn',
        '.env': 'vscode-icons:file-type-dotenv',
        '.env.example': 'vscode-icons:file-type-dotenv',
        '.vscode/settings.json': 'vscode-icons:file-type-vscode',
        'nuxt': 'vscode-icons:file-type-nuxt',
        '.nuxtrc': 'vscode-icons:file-type-nuxt',
        '.nuxtignore': 'vscode-icons:file-type-nuxt',
        'nuxt.config.js': 'vscode-icons:file-type-nuxt',
        'nuxt.config.ts': 'vscode-icons:file-type-nuxt',
        'nuxt.schema.ts': 'vscode-icons:file-type-nuxt',
        'tailwind.config.js': 'vscode-icons:file-type-tailwind',
        'tailwind.config.ts': 'vscode-icons:file-type-tailwind',
        'vue': 'vscode-icons:file-type-vue',
        'ts': 'vscode-icons:file-type-typescript',
        'tsx': 'vscode-icons:file-type-typescript',
        'sql': 'vscode-icons:file-type-sql',
        'mjs': 'vscode-icons:file-type-js',
        'cjs': 'vscode-icons:file-type-js',
        'js': 'vscode-icons:file-type-js',
        'jsx': 'vscode-icons:file-type-js',
        'md': 'vscode-icons:file-type-markdown',
        'mdc': 'vscode-icons:file-type-markdown',
        'py': 'vscode-icons:file-type-python',
        'npm': 'vscode-icons:file-type-npm',
        'pnpm': 'vscode-icons:file-type-pnpm',
        'npx': 'vscode-icons:file-type-npm',
        'yarn': 'vscode-icons:file-type-yarn',
        'bun': 'vscode-icons:file-type-bun',
        'yml': 'vscode-icons:file-type-yaml',
        'json': 'vscode-icons:file-type-json',
        'terminal': 'mdi:terminal-line',
      },
    },
    footer: {
      credits: 'Copyright © 2024',
      links: [
        {
          title: 'shadcn-vue',
          to: 'https://www.shadcn-vue.com/',
          target: '_blank',
        },
        {
          icon: 'mdi:github',
          to: 'https://github.com/Nuxtbe/nuxtbe',
          target: '_blank',
        },
      ],
    },
    toc: {
      enable: true,
      title: 'On This Page',
      links: [{
        title: 'Star on GitHub',
        icon: 'line-md:star-alt',
        to: 'https://github.com/Nuxtbe/nuxtbe',
        target: '_blank',
      }, {
        title: 'Create Issues',
        icon: 'line-md:alert-circle',
        to: 'https://github.com/Nuxtbe/nuxtbe/issues',
        target: '_blank',
      }],
    },
    search: {
      inAside: false,
      style: 'input',
      placeholder: 'Search...',
      placeholderDetailed: 'Search documentation...',
    },
  },
});
